README.md
=> README: updated for OpenVINO installation

README.md
=> README: updated linkage to github

README.md
=> README: noted user to customize .rviz for specific camera

CHANGELOG.rst
=> CHANGELOG: updated for 0.4.0 release

grasp_library/tests/CMakeLists.txt
=> tests/CMakeLists.txt: fix build dependency issue

docs/tutorials_1_grasp_ros2_with_camera.md, grasp_ros2/rviz2/grasp.rviz
=> grasp.rviz: added back this file

grasp_utils/robot_interface/CMakeLists.txt, grasp_utils/robot_interface/include/robot_interface/control_base.hpp, grasp_utils/robot_interface/include/robot_interface/control_ur.hpp, grasp_utils/robot_interface/src/control_base.cpp, grasp_utils/robot_interface/src/control_ur.cpp
This PR intends to add a function that convert RPY angles to rotation vector, and make checkTCPGoalArrived() to be called in moveToTCP().
=> Solve rotation representation mismatch

grasp_utils/robot_interface/Doxyfile, grasp_utils/robot_interface/include/robot_interface/control_base.hpp, grasp_utils/robot_interface/include/robot_interface/control_ur.hpp, grasp_utils/robot_interface/src/control_ur.cpp, grasp_utils/robot_interface/test/ur_test.cpp
This PR intends to add **moveToJointValues** interface.
=> Add moveToJointValues interface

grasp_utils/robot_interface/include/robot_interface/control_base.hpp, grasp_utils/robot_interface/include/robot_interface/control_ur.hpp, grasp_utils/robot_interface/src/control_base.cpp, grasp_utils/robot_interface/src/control_ur.cpp
This PR intends to add a function that can check if joint value target arrived.
=> Add function to check joint value goal arrived

grasp_utils/robot_interface/CMakeLists.txt, grasp_utils/robot_interface/include/robot_interface/control_base.hpp, grasp_utils/robot_interface/src/control_base.cpp, grasp_utils/robot_interface/test/ur_test.cpp
This PR intends to fix the bug that the orientations of actually arrived pose goal and the input pose goal mismatch. This could be brought by some tf2 and eigen transition problem.
=> Fix rotation mismatch

README.md
added one known issue https://github.com/ros2/geometry2/issues/183
=> README: updated known issue

grasp_tutorials/doc/grasp_planner.rst
=> tutorials grasp planner: fix linkage issue

README.md
=> README: updated linkage to the images

grasp_tutorials/doc/grasp_ros2/install_openvino.md
=> grasp planner tutorials: updated for DLDT 2019_R3

grasp_apps/draw_x/CMakeLists.txt, grasp_apps/draw_x/launch/draw_x.launch.py, grasp_apps/draw_x/launch/draw_x.yaml, grasp_apps/draw_x/package.xml, grasp_apps/draw_x/src/draw_x.cpp, grasp_utils/robot_interface/CMakeLists.txt, grasp_utils/robot_interface/src/control_ur.cpp
This PR intends to add draw_x app.
=> Add draw x app

grasp_apps/fixed_position_pick/CMakeLists.txt, grasp_apps/fixed_position_pick/launch/fixed_position_pick.launch.py, grasp_apps/fixed_position_pick/launch/fixed_position_pick.yaml, grasp_apps/fixed_position_pick/package.xml, grasp_apps/fixed_position_pick/src/fixed_position_pick.cpp
This PR intends to add fixed position pick app.
=> Add fixed position pick app

grasp_apps/draw_x/src/draw_x.cpp, grasp_apps/fixed_position_pick/src/fixed_position_pick.cpp, grasp_utils/robot_interface/README.md
This PR intends to fix eigen build instruction and add time delay to fixed_position_pick app.
=> Update robot_interface readme for eigen build

grasp_utils/handeye_dashboard/README.md, grasp_utils/handeye_dashboard/src/handeye_dashboard/handeye_calibration.py
This PR intends to fix handeye_dashboard file storage path error.
=> Fix handeye_dashboard file storage path error

grasp_apps/random_pick/cfg/random_pick.yaml, grasp_apps/recognize_pick/cfg/recognize_pick.yaml, grasp_ros2/cfg/grasp_ros2_params.yaml, grasp_ros2/include/grasp_library/ros2/grasp_detector_gpd.hpp, grasp_ros2/src/grasp_detector_gpd.cpp, grasp_tutorials/doc/recognize_pick.rst
=> grasp_app: updated parameters for ros2 realsense

grasp_tutorials/doc/random_pick.rst, grasp_tutorials/doc/recognize_pick.rst, grasp_utils/handeye_dashboard/README.md
=> app tutorials: updated hand-eye launch command

CHANGELOG.rst, README.md, grasp_msgs/package.xml, grasp_utils/robot_interface/package.xml, moveit_msgs_light/package.xml
=> version: bump up to 0.5.0

docker/Dockerfile, docker/README.md, docker/script/00_ros2_install.sh, docker/script/01_openvino_install.sh, docker/script/02_opencv_install.sh, docker/script/03_librealsense_install.sh, docker/script/04_libpcl_install.sh, docker/script/05_gpg_install.sh, docker/script/06_gpd_install.sh, docker/script/07_ur_modern_driver_install.sh, docker/script/08_ros2_other_deps.sh, docker/script/install_ros2_grasp_library_deps.sh, docker/script/ros_entrypoint.sh, docker/setup_docker_display.sh
Use Github Action to implement CI function. #73 
Add Docker. #24
=> Enable github ci function

grasp_apps/random_pick/CMakeLists.txt, grasp_apps/random_pick/cfg/random_pick.yaml, grasp_apps/random_pick/src/random_pick.cpp, grasp_apps/recognize_pick/CMakeLists.txt, grasp_apps/recognize_pick/cfg/recognize_pick.yaml, grasp_ros2/CMakeLists.txt, grasp_ros2/cfg/grasp_ros2_params.yaml, grasp_ros2/cfg/random_pick.yaml, grasp_ros2/cfg/recognize_pick.yaml, grasp_ros2/include/grasp_library/ros2/grasp_detector_gpd.hpp, grasp_ros2/src/grasp_detector_gpd.cpp, grasp_tutorials/doc/random_pick.rst, grasp_tutorials/doc/recognize_pick.rst
To avoid building all dependent packages for random pick app.
=> Default RECOGNIZE_PICK=OFF
